default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: line-app-dev

test:
  <<: *default
  database: line-app-test

production:
  <<: *default
  database: line-app-pro
